# Deploy static content for main (production) & dev (staging)
name: Deploy static content to Pages

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- 正式站 (main branch) ---
      - name: Deploy to production (GitHub Pages)
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: '.'

      # --- 測試站 (dev branch) ---
      - name: Deploy to staging repo (dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEV_PAGES_TOKEN }}
          external_repository: Sample-Demo-Project/travel-website-demo-dev
          publish_branch: gh-pages
          publish_dir: '.'

      - name: Print staging URL
        if: github.ref == 'refs/heads/dev'
        run: echo "Staging site: https://sample-demo-project.github.io/travel-website-demo-dev/"